### PR TITLE
cell_topic_heatmap color_dictionary can't be None

### PR DESCRIPTION
**Pull request by camiel-m**
#129  I ran into this same issue and added some code to check if the color_dict exists and if not to generate a simple one using matplotlib.colormaps

### CODE REVIEW

**Comment by SeppeDeWinter** [comment]
Thanks for the PR!

Looking again at the code I noticed that the case where variables is None is also not handled correctly (hence the extra changes).

When a variable is not present in the color_dictionary a random color was already assigned.
If you prefer this to be colors from tab20, or another color map from matplotlib, feel free to change this.

@camiel-m could you check wether the code is working?

Thanks,

Seppe

**Comment by camiel-m** [comment]
`color_dict = None` is now working fine, but if you don't specify any variables you get the following error:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File /lustre1/project/stg_00002/mambaforge/vsc47852/envs/scenicplus/lib/python3.11/site-packages/pandas/core/indexes/base.py:3800, in Index.get_loc(self, key, method, tolerance)
   3799 try:
-> 3800     return self._engine.get_loc(casted_key)
   3801 except KeyError as err:

File /lustre1/project/stg_00002/mambaforge/vsc47852/envs/scenicplus/lib/python3.11/site-packages/pandas/_libs/index.pyx:138, in pandas._libs.index.IndexEngine.get_loc()

File /lustre1/project/stg_00002/mambaforge/vsc47852/envs/scenicplus/lib/python3.11/site-packages/pandas/_libs/index.pyx:165, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:5745, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:5753, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: None

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[13], line 2
      1 key = 'pycisTopic_leiden_10_0.3'
----> 2 cell_topic_heatmap(
      3     cistopic_obj,
      4     scale = False,
      5     legend_loc_x = 1.0,
      6     legend_loc_y = -1.2,
      7     legend_dist_y = -1,
      8     figsize = (10, 10)
      9 )

File /lustre1/project/stg_00002/lcb/cmannens/git_repos/pycisTopic/src/pycisTopic/clust_vis.py:933, in cell_topic_heatmap(cistopic_obj, variables, remove_nan, scale, cluster_topics, color_dictionary, seed, legend_loc_x, legend_loc_y, legend_dist_y, figsize, selected_topics, selected_cells, harmony, save)
    926 if scale:
    927     cell_topic = pd.DataFrame(
    928         sklearn.preprocessing.StandardScaler().fit_transform(cell_topic),
    929         index=cell_topic.index.to_list(),
    930         columns=cell_topic.columns,
    931     )
--> 933 if remove_nan and (sum(cell_data[variables].isnull().sum()) > 0):
    934     cell_data = cell_data[variables].dropna()
    935     cell_topic = cell_topic.loc[:, cell_data.index.tolist()]

File /lustre1/project/stg_00002/mambaforge/vsc47852/envs/scenicplus/lib/python3.11/site-packages/pandas/core/frame.py:3805, in DataFrame.__getitem__(self, key)
   3803 if self.columns.nlevels > 1:
   3804     return self._getitem_multilevel(key)
-> 3805 indexer = self.columns.get_loc(key)
   3806 if is_integer(indexer):
   3807     indexer = [indexer]

File /lustre1/project/stg_00002/mambaforge/vsc47852/envs/scenicplus/lib/python3.11/site-packages/pandas/core/indexes/base.py:3802, in Index.get_loc(self, key, method, tolerance)
   3800     return self._engine.get_loc(casted_key)
   3801 except KeyError as err:
-> 3802     raise KeyError(key) from err
   3803 except TypeError:
   3804     # If we have a listlike key, _check_indexing_error will raise
   3805     #  InvalidIndexError. Otherwise we fall through and re-raise
   3806     #  the TypeError.
   3807     self._check_indexing_error(key)

KeyError: None
```

maybe a simple change like this would be enough?
```
    if variables:
        if remove_nan and (sum(cell_data[variables].isnull().sum()) > 0):
            cell_data = cell_data[variables].dropna()
            cell_topic = cell_topic.loc[:, cell_data.index.tolist()]
```

**Comment by SeppeDeWinter** [comment]
Ah yes, right!

Should be fixed now (I hope).

**Comment by camiel-m** [comment]
It doesn't throw an error, but the plot does look quite different from default behavior. The axis are flipped and the cells are not sorted. Is this the intended behavior or should the cells maybe sorted based on similarity or by highest topic score?
download

**Comment by SeppeDeWinter** [comment]
hmm yes. does not look super informative.

How about when you set `cluster_topics` to `True` (it's False by default)

**Comment by camiel-m** [comment]
It's a lot more interpretable that way.
download

**Comment by SeppeDeWinter** [comment]
Great!!

**Pull request merged**
